name: delivery_boy
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+7

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.0
  dio: ^4.0.6
  get: ^4.6.5
  # carousel_slider: ^3.0.0
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  # pin_code_fields: ^7.4.0
  font_awesome_flutter: ^10.2.1
  # rating_bar: ^0.2.0
  google_maps_flutter: ^2.2.1
  geocode: ^1.0.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  # flutter_launcher_icons: ^0.9.3
  # carousel_pro: ^1.0.0
  connectivity_plus: ^2.3.7
  simple_fontellico_progress_dialog: ^0.2.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  # flutter_slidable: ^1.3.1
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.4
  bot_toast: ^4.0.3
  firebase_messaging: ^11.2.10
  firebase_core: ^1.13.1
  flutter_screenutil: ^5.3.1
  flutter_google_places: ^0.3.0
  google_place: ^0.4.7
  vibration: ^1.7.6
  shimmer: ^2.0.0
  intl: ^0.17.0
  skeleton_text: ^3.0.0
  awesome_notifications: ^0.6.21
  sunmi_printer_plus: ^2.1.1
  esc_pos_utils: ^1.1.0
  
  # convex_bottom_bar: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf

  
  assets:
    - assets/svg/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    

  
